name: PyTest
on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: 'CPython 3.11', python: '3.11'}
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          pip install -r requirements_dev.txt

      - name: Run test suite
        run: |
          pytest

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: astral-sh/ruff-action@v1